### ISSUE TITLE
Inconsistent behavior for near zero sigma

### ISSUE THREAD

**Issue by jknowles** [ggopalan/FastGP#2]
@ggopalan Thanks for the patch. I have run into a new problem. 

In `rcpp_rmvnorm_stable` there is a problem when `rcppeigen_get_chol_diag` returns a value of 0. This happens if the user passes a sigma matrix that is 1x1 and is very small. In this case, the code `diag(sqrt(rcppeigen_get_chol_diag(S)))`, which is now `diag(sqrt(0))` will return an empty 0x0 matrix. This causes a failure in the matrix multiplication because of non-comformable arrays in the final step. 

From the `diag` documentation, this is because `diag` has a distinct behavior when it is given only a scalar: 

>  x is a scalar (length-one vector) and the only argument, it returns a square identity matrix of size > > given by the scalar.

To avoid this problem for univariate normal sampling, the result of `sqrt(rcppeigen_get_chol_diag(S))` should be checked to ensure it is a matrix, in which case diag will return the correct values.

**Comment by ggopalan** [comment]
Thanks Jared for this note; I have changed rcpp_rmvnorm_stable to test the
case that the input is univariate. Please see the latest version on github
and let me know if it fixes your issue. If so, I will push to CRAN.

On Fri, Jan 22, 2016 at 11:52 AM, Jared Knowles <notifications@github.com>
wrote:

> @ggopalan <https://github.com/ggopalan> Thanks for the patch. I have run
> into a new problem.
>
> In rcpp_rmvnorm_stable there is a problem when rcppeigen_get_chol_diag
> returns a value of 0. This happens if the user passes a sigma matrix that
> is 1x1 and is very small. In this case, the code
> diag(sqrt(rcppeigen_get_chol_diag(S))), which is now diag(sqrt(0)) will
> return an empty 0x0 matrix. This causes a failure in the matrix
> multiplication because of non-comformable arrays in the final step.
>
> From the diag documentation, this is because diag has a distinct behavior
> when it is given only a scalar:
>
> x is a scalar (length-one vector) and the only argument, it returns a
> square identity matrix of size > > given by the scalar.
>
> To avoid this problem for univariate normal sampling, the result of
> sqrt(rcppeigen_get_chol_diag(S)) should be checked to ensure it is a
> matrix, in which case diag will return the correct values.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ggopalan/FastGP/issues/2>.
>



-- 
Best,
Giri

**Comment by jknowles** [comment]
Not to be a bother, but this still produces an error -- albeit now we've scoped it down. 

In some cases `rcppeigen_get_chol_diag` will return a number which is very nearly zero, but is negative. In this case, the sqrt function returns NaN and the sampler produces a vector of NaN the length of n. 

You can reproduce this behavior with this example:

```r
S <- structure(c(0.499821699631263, 0.336243313530159, 
                          0.336243313530159, 0.226199794801124), .Dim = c(2L, 2L))
mu <- structure(c(-0.404870840284113, -0.27236735217639), .Names = c("(Intercept)", 
"HEIGHT"))
n.sims <- 10
FastGP::rcpp_rmvnorm_stable(n= n.sims,
                                       mu = mu,
                                       S = S)
```

If you run `rcppeigen_get_chol_diag(S)` you see this:

```
FastGP::rcppeigen_get_chol_diag(S)
[1]  4.998217e-01 -2.775558e-17
```

I don't know if you want to clutter up the `rcpp_rmvnorm_stable` function with an absolute value call. It seems to me it is safer to ensure that `rcppeigen_get_chol_diag` returns the absolute value, or 0, in cases where an extremely small, close to zero value winds up being negative.

**Comment by ggopalan** [comment]
Thanks for the continued feedback!

This is a bit unfortunate but an appropriate patch is to simply set such
values to 0, which I will work on shortly.

Best - Giri

On Mon, Jan 25, 2016 at 11:08 AM, Jared Knowles <notifications@github.com>
wrote:

> Not to be a bother, but this still produces an error -- albeit now we've
> scoped it down.
>
> In some cases rcppeigen_get_chol_diag will return a number which is very
> nearly zero, but is negative. In this case, the sqrt function returns NaN
> and the sampler produces a vector of NaN the length of n.
>
> You can reproduce this behavior with this example:
>
> S <- structure(c(0.499821699631263, 0.336243313530159,
>                           0.336243313530159, 0.226199794801124), .Dim = c(2L, 2L))mu <- structure(c(-0.404870840284113, -0.27236735217639), .Names = c("(Intercept)", "HEIGHT"))n.sims <- 10FastGP::rcpp_rmvnorm_stable(n= n.sims,
>                                        mu = mu,
>                                        S = S)
>
> If you run rcppeigen_get_chol_diag(S) you see this:
>
> FastGP::rcppeigen_get_chol_diag(S)
> [1]  4.998217e-01 -2.775558e-17
>
> I don't know if you want to clutter up the rcpp_rmvnorm_stable function
> with an absolute value call. It seems to me it is safer to ensure that
> rcppeigen_get_chol_diag returns the absolute value, or 0, in cases where
> an extremely small, close to zero value winds up being negative.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ggopalan/FastGP/issues/2#issuecomment-174556662>.
>



-- 
Best,
Giri

**Comment by jknowles** [comment]
Great -- I think this is fixed now. Let me know when you push it to CRAN and I will then be able to push my updated package to CRAN as well. I have referenced you in both the documentation and the NEWS file of the package. Thanks for the great work.
